Работа с DOM. Загрузка документа
js-tasks-ru/js-20220111_alex-belost pull request #5
Opened 2022-01-27 19:14 UTC by alex-belost

- Notification component
- Sortable table v1

2022-01-27 19:15 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-01-27 22:34 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(target) {
может тут также использовать значение по умолчанию?
```
show(target = document.body) {
```

2022-01-27 22:35 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const existNotificationElement = document.querySelector('.notification');
попробуйте избавиться от обращения к `DOM` и проверить наличие предыдущего нотификейшена другим способом

2022-01-27 22:36 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +const SORT_ORDERS = {
тот же вопрос: почему эти значения хранятся за пределами класса?

2022-01-27 22:37 UTC, dosandk requested changes
решение `NotificationMessage` следует поправить

2022-01-28 07:19 UTC, alex-belost commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +const SORT_ORDERS = {
своего рода декомпозиция, набор значений по умолчанию и инкапсуляция дефолтных значений внутри файла, в идеале я бы их вынес в отдельный файл

2022-01-28 16:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-01 15:56 UTC, dosandk approved these changes
👍 good

2022-02-01 15:57 UTC, merged