[06-events-practice][07-async-code-fetch-api-part-1]
js-tasks-ru/js-20220111_alex-belost pull request #9
Opened 2022-02-07 20:02 UTC by alex-belost

2022-02-07 20:03 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-07 20:05 UTC, alex-belost commented
Uptodate

2022-02-07 20:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-07 22:38 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements.header.removeEventListener('click', this.onSort.bind(this));
так делать категорически нельзя!
`bind` создаст новую функцию, а для удаления следует передать именно ту функцию которую добавляли в качестве обработчика события в метод `addEventListeners`

2022-02-07 22:38 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    const entries = Array.from(
👍

2022-02-07 22:38 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static instance = null;
👍 лайк за использование статического свойства

2022-02-07 22:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener('pointerover', this.onPointerOver.bind(this));
так делать также нельзя! 
проверьте удалены ли эти обработчики событий после вызова `destroy`

2022-02-07 22:40 UTC, dosandk commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.element.dispatchEvent(new CustomEvent('data:change', { detail: data }));
пользовательские события, обычно именуются через `-`, но в проектах, конечно, могут быть и другие соглашения, в виде `:` как разделителя

2022-02-07 22:41 UTC, dosandk requested changes
работы неплохие, но во всех задачах следует поправить `bind` в обработчиках событий! Проверьте удаляются ли такие обработчики (подсказка: нет)

2022-02-08 19:35 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-08 19:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-08 19:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-02-08 19:41 UTC, alex-belost commented on 07-async-code-fetch-api-part-1/1-column-chart/index.js
> +    this.element.dispatchEvent(new CustomEvent('data:change', { detail: data }));
уже как то в привычку вошла такая запись, выглядит как ключ/значение, удобно :)

2022-02-08 19:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-10 22:31 UTC, dosandk approved these changes
👍 good

2022-02-10 22:32 UTC, merged